// Code generated by microgen 0.9.0. DO NOT EDIT.

package transport

type (
	SumRequest struct {
		A int `json:"a"`
		B int `json:"b"`
	}
	SumResponse struct {
		Result int `json:"result"`
	}

	ConcatRequest struct {
		A string `json:"a"`
		B string `json:"b"`
	}
	ConcatResponse struct {
		Result string `json:"result"`
	}
)
