// Code generated by microgen. DO NOT EDIT.

package transport

import (
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	opentracinggo "github.com/opentracing/opentracing-go"
)

func TraceClient(tracer opentracinggo.Tracer) func(endpoints Endpoints) Endpoints {
	return func(endpoints Endpoints) Endpoints {
		return Endpoints{
			CreateComment_Endpoint:   opentracing.TraceClient(tracer, "CreateComment")(endpoints.CreateComment_Endpoint),
			CreateUser_Endpoint:      opentracing.TraceClient(tracer, "CreateUser")(endpoints.CreateUser_Endpoint),
			FindUsers_Endpoint:       opentracing.TraceClient(tracer, "FindUsers")(endpoints.FindUsers_Endpoint),
			GetComment_Endpoint:      opentracing.TraceClient(tracer, "GetComment")(endpoints.GetComment_Endpoint),
			GetUserComments_Endpoint: opentracing.TraceClient(tracer, "GetUserComments")(endpoints.GetUserComments_Endpoint),
			GetUser_Endpoint:         opentracing.TraceClient(tracer, "GetUser")(endpoints.GetUser_Endpoint),
			UpdateUser_Endpoint:      opentracing.TraceClient(tracer, "UpdateUser")(endpoints.UpdateUser_Endpoint),
		}
	}
}
