// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/api.proto

package pb // import "github.com/cv21/microgen/examples/usersvc/pb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateUser_Request struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUser_Request) Reset()         { *m = CreateUser_Request{} }
func (m *CreateUser_Request) String() string { return proto.CompactTextString(m) }
func (*CreateUser_Request) ProtoMessage()    {}
func (*CreateUser_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_20f8df7daf6e3a48, []int{0}
}
func (m *CreateUser_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUser_Request.Unmarshal(m, b)
}
func (m *CreateUser_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUser_Request.Marshal(b, m, deterministic)
}
func (dst *CreateUser_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUser_Request.Merge(dst, src)
}
func (m *CreateUser_Request) XXX_Size() int {
	return xxx_messageInfo_CreateUser_Request.Size(m)
}
func (m *CreateUser_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUser_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUser_Request proto.InternalMessageInfo

func (m *CreateUser_Request) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUser_Request struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUser_Request) Reset()         { *m = UpdateUser_Request{} }
func (m *UpdateUser_Request) String() string { return proto.CompactTextString(m) }
func (*UpdateUser_Request) ProtoMessage()    {}
func (*UpdateUser_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_20f8df7daf6e3a48, []int{1}
}
func (m *UpdateUser_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUser_Request.Unmarshal(m, b)
}
func (m *UpdateUser_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUser_Request.Marshal(b, m, deterministic)
}
func (dst *UpdateUser_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUser_Request.Merge(dst, src)
}
func (m *UpdateUser_Request) XXX_Size() int {
	return xxx_messageInfo_UpdateUser_Request.Size(m)
}
func (m *UpdateUser_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUser_Request.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUser_Request proto.InternalMessageInfo

func (m *UpdateUser_Request) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetUser_Response struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUser_Response) Reset()         { *m = GetUser_Response{} }
func (m *GetUser_Response) String() string { return proto.CompactTextString(m) }
func (*GetUser_Response) ProtoMessage()    {}
func (*GetUser_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_20f8df7daf6e3a48, []int{2}
}
func (m *GetUser_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUser_Response.Unmarshal(m, b)
}
func (m *GetUser_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUser_Response.Marshal(b, m, deterministic)
}
func (dst *GetUser_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUser_Response.Merge(dst, src)
}
func (m *GetUser_Response) XXX_Size() int {
	return xxx_messageInfo_GetUser_Response.Size(m)
}
func (m *GetUser_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUser_Response.DiscardUnknown(m)
}

var xxx_messageInfo_GetUser_Response proto.InternalMessageInfo

func (m *GetUser_Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type FindUsers_Response struct {
	Results              []*User  `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindUsers_Response) Reset()         { *m = FindUsers_Response{} }
func (m *FindUsers_Response) String() string { return proto.CompactTextString(m) }
func (*FindUsers_Response) ProtoMessage()    {}
func (*FindUsers_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_20f8df7daf6e3a48, []int{3}
}
func (m *FindUsers_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUsers_Response.Unmarshal(m, b)
}
func (m *FindUsers_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUsers_Response.Marshal(b, m, deterministic)
}
func (dst *FindUsers_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUsers_Response.Merge(dst, src)
}
func (m *FindUsers_Response) XXX_Size() int {
	return xxx_messageInfo_FindUsers_Response.Size(m)
}
func (m *FindUsers_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUsers_Response.DiscardUnknown(m)
}

var xxx_messageInfo_FindUsers_Response proto.InternalMessageInfo

func (m *FindUsers_Response) GetResults() []*User {
	if m != nil {
		return m.Results
	}
	return nil
}

type CreateComment_Request struct {
	Comment              *Comment `protobuf:"bytes,1,opt,name=comment" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateComment_Request) Reset()         { *m = CreateComment_Request{} }
func (m *CreateComment_Request) String() string { return proto.CompactTextString(m) }
func (*CreateComment_Request) ProtoMessage()    {}
func (*CreateComment_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_20f8df7daf6e3a48, []int{4}
}
func (m *CreateComment_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateComment_Request.Unmarshal(m, b)
}
func (m *CreateComment_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateComment_Request.Marshal(b, m, deterministic)
}
func (dst *CreateComment_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateComment_Request.Merge(dst, src)
}
func (m *CreateComment_Request) XXX_Size() int {
	return xxx_messageInfo_CreateComment_Request.Size(m)
}
func (m *CreateComment_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateComment_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CreateComment_Request proto.InternalMessageInfo

func (m *CreateComment_Request) GetComment() *Comment {
	if m != nil {
		return m.Comment
	}
	return nil
}

type GetComment_Response struct {
	Comment              *Comment `protobuf:"bytes,1,opt,name=comment" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetComment_Response) Reset()         { *m = GetComment_Response{} }
func (m *GetComment_Response) String() string { return proto.CompactTextString(m) }
func (*GetComment_Response) ProtoMessage()    {}
func (*GetComment_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_20f8df7daf6e3a48, []int{5}
}
func (m *GetComment_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetComment_Response.Unmarshal(m, b)
}
func (m *GetComment_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetComment_Response.Marshal(b, m, deterministic)
}
func (dst *GetComment_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetComment_Response.Merge(dst, src)
}
func (m *GetComment_Response) XXX_Size() int {
	return xxx_messageInfo_GetComment_Response.Size(m)
}
func (m *GetComment_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_GetComment_Response.DiscardUnknown(m)
}

var xxx_messageInfo_GetComment_Response proto.InternalMessageInfo

func (m *GetComment_Response) GetComment() *Comment {
	if m != nil {
		return m.Comment
	}
	return nil
}

type GetUserComments_Response struct {
	List                 []*Comment `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetUserComments_Response) Reset()         { *m = GetUserComments_Response{} }
func (m *GetUserComments_Response) String() string { return proto.CompactTextString(m) }
func (*GetUserComments_Response) ProtoMessage()    {}
func (*GetUserComments_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_20f8df7daf6e3a48, []int{6}
}
func (m *GetUserComments_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserComments_Response.Unmarshal(m, b)
}
func (m *GetUserComments_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserComments_Response.Marshal(b, m, deterministic)
}
func (dst *GetUserComments_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserComments_Response.Merge(dst, src)
}
func (m *GetUserComments_Response) XXX_Size() int {
	return xxx_messageInfo_GetUserComments_Response.Size(m)
}
func (m *GetUserComments_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserComments_Response.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserComments_Response proto.InternalMessageInfo

func (m *GetUserComments_Response) GetList() []*Comment {
	if m != nil {
		return m.List
	}
	return nil
}

type Comment struct {
	Id                   string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Text                 string                `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	Title                *wrappers.StringValue `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Comment) Reset()         { *m = Comment{} }
func (m *Comment) String() string { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()    {}
func (*Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_20f8df7daf6e3a48, []int{7}
}
func (m *Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comment.Unmarshal(m, b)
}
func (m *Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comment.Marshal(b, m, deterministic)
}
func (dst *Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comment.Merge(dst, src)
}
func (m *Comment) XXX_Size() int {
	return xxx_messageInfo_Comment.Size(m)
}
func (m *Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Comment proto.InternalMessageInfo

func (m *Comment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Comment) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Comment) GetTitle() *wrappers.StringValue {
	if m != nil {
		return m.Title
	}
	return nil
}

type User struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Gender               int64      `protobuf:"varint,3,opt,name=gender" json:"gender,omitempty"`
	Comments             []*Comment `protobuf:"bytes,4,rep,name=comments" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_20f8df7daf6e3a48, []int{8}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetGender() int64 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *User) GetComments() []*Comment {
	if m != nil {
		return m.Comments
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateUser_Request)(nil), "devimteam.proto.CreateUser_Request")
	proto.RegisterType((*UpdateUser_Request)(nil), "devimteam.proto.UpdateUser_Request")
	proto.RegisterType((*GetUser_Response)(nil), "devimteam.proto.GetUser_Response")
	proto.RegisterType((*FindUsers_Response)(nil), "devimteam.proto.FindUsers_Response")
	proto.RegisterType((*CreateComment_Request)(nil), "devimteam.proto.CreateComment_Request")
	proto.RegisterType((*GetComment_Response)(nil), "devimteam.proto.GetComment_Response")
	proto.RegisterType((*GetUserComments_Response)(nil), "devimteam.proto.GetUserComments_Response")
	proto.RegisterType((*Comment)(nil), "devimteam.proto.Comment")
	proto.RegisterType((*User)(nil), "devimteam.proto.User")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserService service

type UserServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUser_Request, opts ...grpc.CallOption) (*wrappers.StringValue, error)
	UpdateUser(ctx context.Context, in *UpdateUser_Request, opts ...grpc.CallOption) (*empty.Empty, error)
	GetUser(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*GetUser_Response, error)
	FindUsers(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*FindUsers_Response, error)
	CreateComment(ctx context.Context, in *CreateComment_Request, opts ...grpc.CallOption) (*wrappers.StringValue, error)
	GetComment(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*GetComment_Response, error)
	GetUserComments(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*GetUserComments_Response, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUser_Request, opts ...grpc.CallOption) (*wrappers.StringValue, error) {
	out := new(wrappers.StringValue)
	err := grpc.Invoke(ctx, "/devimteam.proto.UserService/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpdateUser_Request, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := grpc.Invoke(ctx, "/devimteam.proto.UserService/UpdateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*GetUser_Response, error) {
	out := new(GetUser_Response)
	err := grpc.Invoke(ctx, "/devimteam.proto.UserService/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) FindUsers(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*FindUsers_Response, error) {
	out := new(FindUsers_Response)
	err := grpc.Invoke(ctx, "/devimteam.proto.UserService/FindUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateComment(ctx context.Context, in *CreateComment_Request, opts ...grpc.CallOption) (*wrappers.StringValue, error) {
	out := new(wrappers.StringValue)
	err := grpc.Invoke(ctx, "/devimteam.proto.UserService/CreateComment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetComment(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*GetComment_Response, error) {
	out := new(GetComment_Response)
	err := grpc.Invoke(ctx, "/devimteam.proto.UserService/GetComment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserComments(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*GetUserComments_Response, error) {
	out := new(GetUserComments_Response)
	err := grpc.Invoke(ctx, "/devimteam.proto.UserService/GetUserComments", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	CreateUser(context.Context, *CreateUser_Request) (*wrappers.StringValue, error)
	UpdateUser(context.Context, *UpdateUser_Request) (*empty.Empty, error)
	GetUser(context.Context, *wrappers.StringValue) (*GetUser_Response, error)
	FindUsers(context.Context, *empty.Empty) (*FindUsers_Response, error)
	CreateComment(context.Context, *CreateComment_Request) (*wrappers.StringValue, error)
	GetComment(context.Context, *wrappers.StringValue) (*GetComment_Response, error)
	GetUserComments(context.Context, *wrappers.StringValue) (*GetUserComments_Response, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUser_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devimteam.proto.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUser_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUser_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devimteam.proto.UserService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*UpdateUser_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devimteam.proto.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*wrappers.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_FindUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).FindUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devimteam.proto.UserService/FindUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).FindUsers(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateComment_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devimteam.proto.UserService/CreateComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateComment(ctx, req.(*CreateComment_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devimteam.proto.UserService/GetComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetComment(ctx, req.(*wrappers.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devimteam.proto.UserService/GetUserComments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserComments(ctx, req.(*wrappers.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "devimteam.proto.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "FindUsers",
			Handler:    _UserService_FindUsers_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _UserService_CreateComment_Handler,
		},
		{
			MethodName: "GetComment",
			Handler:    _UserService_GetComment_Handler,
		},
		{
			MethodName: "GetUserComments",
			Handler:    _UserService_GetUserComments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/api.proto",
}

func init() { proto.RegisterFile("pb/api.proto", fileDescriptor_api_20f8df7daf6e3a48) }

var fileDescriptor_api_20f8df7daf6e3a48 = []byte{
	// 509 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xdf, 0x6f, 0xd3, 0x30,
	0x10, 0xc7, 0xd5, 0x36, 0xac, 0xec, 0x06, 0x0c, 0x19, 0x6d, 0x8a, 0x02, 0x42, 0x23, 0x20, 0xc4,
	0x24, 0x94, 0x48, 0x65, 0xe2, 0x05, 0x21, 0x24, 0xa6, 0xb1, 0x0d, 0x1e, 0x40, 0x99, 0xca, 0xc3,
	0x5e, 0x50, 0x7e, 0x1c, 0xc1, 0x52, 0x9c, 0x18, 0xdb, 0x29, 0xe5, 0xff, 0xe3, 0x0f, 0x43, 0x71,
	0xdc, 0x06, 0xea, 0x66, 0x15, 0xec, 0x2d, 0x3e, 0x9f, 0x3f, 0x77, 0xdf, 0xeb, 0x7d, 0x0b, 0xb7,
	0x78, 0x12, 0xc6, 0x9c, 0x06, 0x5c, 0x54, 0xaa, 0x22, 0xbb, 0x19, 0xce, 0x28, 0x53, 0x18, 0xb3,
	0x36, 0xe0, 0xdd, 0xcf, 0xab, 0x2a, 0x2f, 0x30, 0xd4, 0xa7, 0xa4, 0xfe, 0x1a, 0x22, 0xe3, 0xea,
	0xa7, 0xb9, 0x7c, 0xb8, 0x7a, 0xf9, 0x43, 0xc4, 0x9c, 0xa3, 0x90, 0xed, 0xbd, 0xff, 0x06, 0xc8,
	0xb1, 0xc0, 0x58, 0xe1, 0x54, 0xa2, 0xf8, 0x12, 0xe1, 0xf7, 0x1a, 0xa5, 0x22, 0x87, 0xe0, 0xd4,
	0x12, 0x85, 0x3b, 0x38, 0x18, 0x3c, 0xdb, 0x99, 0xec, 0x05, 0x2b, 0x25, 0x83, 0x26, 0x39, 0xd2,
	0x29, 0x0d, 0x60, 0xca, 0xb3, 0x6b, 0x00, 0x5e, 0xc3, 0xdd, 0x53, 0x54, 0xe6, 0xb5, 0xe4, 0x55,
	0x29, 0xf1, 0x5f, 0x9e, 0x9f, 0x00, 0x79, 0x47, 0xcb, 0xac, 0x89, 0xc8, 0x0e, 0x10, 0xc2, 0x58,
	0xa0, 0xac, 0x0b, 0x25, 0xdd, 0xc1, 0xc1, 0xa8, 0x9f, 0xb1, 0xc8, 0xf2, 0x3f, 0xc0, 0x5e, 0x3b,
	0x87, 0xe3, 0x8a, 0x31, 0x2c, 0xd5, 0x52, 0xc9, 0x04, 0xc6, 0x69, 0x1b, 0x32, 0xdd, 0xb8, 0x16,
	0xc9, 0x3c, 0x89, 0x16, 0x89, 0xfe, 0x39, 0xdc, 0x3b, 0x45, 0xd5, 0x91, 0x4c, 0x53, 0xff, 0x83,
	0x3a, 0x03, 0xd7, 0x4c, 0xc7, 0x5c, 0xfd, 0x21, 0xf2, 0x39, 0x38, 0x05, 0x95, 0xca, 0x28, 0xec,
	0x87, 0xe9, 0x2c, 0x3f, 0x86, 0xb1, 0x09, 0x90, 0x3b, 0x30, 0xa4, 0x99, 0xee, 0x61, 0x3b, 0x1a,
	0xd2, 0x8c, 0x10, 0x70, 0x14, 0xce, 0x95, 0x3b, 0xd4, 0x11, 0xfd, 0x4d, 0x26, 0x70, 0x43, 0x51,
	0x55, 0xa0, 0x3b, 0xd2, 0xad, 0x3e, 0x08, 0xda, 0x45, 0x0a, 0x16, 0x8b, 0x14, 0x5c, 0x28, 0x41,
	0xcb, 0xfc, 0x73, 0x5c, 0xd4, 0x18, 0xb5, 0xa9, 0xfe, 0x1c, 0x9c, 0xa6, 0xd3, 0x75, 0xfc, 0x32,
	0x66, 0xb8, 0xe0, 0x37, 0xdf, 0x64, 0x1f, 0xb6, 0x72, 0x2c, 0x33, 0x14, 0xba, 0xc0, 0x28, 0x32,
	0x27, 0x72, 0x04, 0x37, 0x8d, 0x76, 0xe9, 0x3a, 0x1b, 0x84, 0x2d, 0x33, 0x27, 0xbf, 0x1c, 0xd8,
	0x69, 0x4a, 0x5f, 0xa0, 0x98, 0xd1, 0x14, 0xc9, 0x47, 0x80, 0x6e, 0xad, 0xc9, 0x63, 0x9b, 0x60,
	0xed, 0xbc, 0x77, 0xa5, 0x42, 0x72, 0x0e, 0xd0, 0xad, 0xf9, 0x1a, 0xa0, 0xed, 0x01, 0x6f, 0xdf,
	0x02, 0x9e, 0x34, 0xc6, 0x24, 0xef, 0x61, 0x6c, 0x7e, 0x52, 0x72, 0x65, 0x4d, 0xef, 0x91, 0x55,
	0xc5, 0x32, 0xca, 0x19, 0x6c, 0x2f, 0xb7, 0x9f, 0xf4, 0x14, 0xf4, 0xec, 0x6e, 0xd7, 0x38, 0x66,
	0x0a, 0xb7, 0xff, 0x32, 0x00, 0x79, 0xda, 0x33, 0xb4, 0x15, 0x83, 0x6c, 0x98, 0xdb, 0x27, 0x80,
	0xce, 0x0a, 0x1b, 0xf4, 0x3e, 0x59, 0xa7, 0xd7, 0x72, 0xd1, 0x25, 0xec, 0xae, 0x38, 0x62, 0x03,
	0xf6, 0xb0, 0x6f, 0x8c, 0x96, 0xa3, 0xde, 0xbe, 0xbc, 0x3c, 0xca, 0xa9, 0xfa, 0x56, 0x27, 0x41,
	0x5a, 0xb1, 0x70, 0xf9, 0x2c, 0x64, 0x34, 0x15, 0x55, 0x8e, 0x65, 0x88, 0xf3, 0x98, 0xf1, 0x02,
	0x65, 0xd8, 0xfc, 0xf7, 0xc8, 0x59, 0x1a, 0xf2, 0xe4, 0x15, 0x4f, 0x92, 0x2d, 0xcd, 0x7d, 0xf1,
	0x3b, 0x00, 0x00, 0xff, 0xff, 0x43, 0xe9, 0xd1, 0x77, 0xaa, 0x05, 0x00, 0x00,
}
