// Code generated by microgen. DO NOT EDIT.

package grpc

import (
	"context"
	transport "github.com/devimteam/microgen/examples/usersvc/pkg/usersvc/transport"
	empty "github.com/golang/protobuf/ptypes/empty"
)

func _Encode_CreateUser_Request(ctx context.Context, request interface{}) (interface{}, error) {
	req := request.(*transport.CreateUser_Request)
	return __CreateUser_Request_ToProtobuf(req)
}

func _Encode_UpdateUser_Request(ctx context.Context, request interface{}) (interface{}, error) {
	req := request.(*transport.UpdateUser_Request)
	return __UpdateUser_Request_ToProtobuf(req)
}

func _Encode_GetUser_Request(ctx context.Context, request interface{}) (interface{}, error) {
	return request
}

func _Encode_FindUsers_Request(ctx context.Context, request interface{}) (interface{}, error) {
	return &empty.Empty{}
}

func _Encode_CreateComment_Request(ctx context.Context, request interface{}) (interface{}, error) {
	req := request.(*transport.CreateComment_Request)
	return __CreateComment_Request_ToProtobuf(req)
}

func _Encode_GetComment_Request(ctx context.Context, request interface{}) (interface{}, error) {
	return request
}

func _Encode_GetUserComments_Request(ctx context.Context, request interface{}) (interface{}, error) {
	return request
}
