// Code generated by microgen 0.9.0. DO NOT EDIT.

package transporthttp

import (
	transport "github.com/devimteam/microgen/examples/addsvc/transport"
	log "github.com/go-kit/kit/log"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	httpkit "github.com/go-kit/kit/transport/http"
	opentracinggo "github.com/opentracing/opentracing-go"
	"net/url"
)

func NewHTTPClient(u *url.URL, opts ...httpkit.ClientOption) transport.EndpointsSet {
	return transport.EndpointsSet{
		ConcatEndpoint: httpkit.NewClient(
			"POST", u,
			_Encode_Concat_Request,
			_Decode_Concat_Response,
			opts...,
		).Endpoint(),
		SumEndpoint: httpkit.NewClient(
			"POST", u,
			_Encode_Sum_Request,
			_Decode_Sum_Response,
			opts...,
		).Endpoint(),
	}
}

func TracingHTTPClientOptions(tracer opentracinggo.Tracer, logger log.Logger) func([]httpkit.ClientOption) []httpkit.ClientOption {
	return func(opts []httpkit.ClientOption) []httpkit.ClientOption {
		return append(opts, httpkit.ClientBefore(
			opentracing.ContextToHTTP(tracer, logger),
		))
	}
}
