// Code generated by microgen 0.9.0. DO NOT EDIT.

package transporthttp

import (
	transport "github.com/devimteam/microgen/examples/addsvc/transport"
	log "github.com/go-kit/kit/log"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	http "github.com/go-kit/kit/transport/http"
	mux "github.com/gorilla/mux"
	opentracinggo "github.com/opentracing/opentracing-go"
	http1 "net/http"
)

func NewHTTPHandler(endpoints *transport.EndpointsSet, logger log.Logger, tracer opentracinggo.Tracer, opts ...http.ServerOption) http1.Handler {
	mux := mux.NewRouter()
	mux.Methods("POST").Path("/sum").Handler(
		http.NewServer(
			endpoints.SumEndpoint,
			_Decode_Sum_Request,
			_Encode_Sum_Response,
			append(opts, http.ServerBefore(
				opentracing.HTTPToContext(tracer, "Sum", logger)))...))
	mux.Methods("POST").Path("/concat").Handler(
		http.NewServer(
			endpoints.ConcatEndpoint,
			_Decode_Concat_Request,
			_Encode_Concat_Response,
			append(opts, http.ServerBefore(
				opentracing.HTTPToContext(tracer, "Concat", logger)))...))
	return mux
}
