// Code generated by microgen 1.0.0-beta. DO NOT EDIT.

// It is better for you if you do not change functions names!
// This file will never be overwritten.
package transportgrpc

import (
	pb "github.com/devimteam/microgen/examples/protobuf"
	service "github.com/devimteam/microgen/examples/usersvc/pkg/usersvc"
)

func UserToProto(user service.User) (pb.User, error) {
	panic("function not provided") // TODO: provide converter
}

func ProtoToUser(protoUser pb.User) (service.User, error) {
	panic("function not provided") // TODO: provide converter
}

func MapStringUserToProto(results map[string]service.User) (map[string]pb.User, error) {
	panic("function not provided") // TODO: provide converter
}

func ProtoToMapStringUser(protoResults map[string]pb.User) (map[string]service.User, error) {
	panic("function not provided") // TODO: provide converter
}

func CommentToProto(comment service.Comment) (pb.Comment, error) {
	panic("function not provided") // TODO: provide converter
}

func ProtoToComment(protoComment pb.Comment) (service.Comment, error) {
	panic("function not provided") // TODO: provide converter
}

func ListCommentToProto(list []service.Comment) ([]pb.Comment, error) {
	panic("function not provided") // TODO: provide converter
}

func ProtoToListComment(protoList []pb.Comment) ([]service.Comment, error) {
	panic("function not provided") // TODO: provide converter
}
