// Code generated by microgen 1.0.0-beta. DO NOT EDIT.

package service

import service "github.com/devimteam/microgen/examples/usersvc/pkg/usersvc"

// Service middleware (closure).
type Middleware func(service.UserService) service.UserService
