// Code generated by microgen 0.9.0. DO NOT EDIT.

package service

import service "github.com/devimteam/microgen/examples/usersvc/pkg/usersvc"

// Service middleware (closure).
type Middleware func(service.UserService) service.UserService
