package template

import (
	"strings"

	"github.com/vetcher/godecl/types"
	. "github.com/vetcher/jennifer/jen"
)

type GRPCClientTemplate struct {
	packageName        string
	PackagePath        string
	ServicePackageName string
}

func (t *GRPCClientTemplate) grpcConverterPackagePath() string {
	return t.PackagePath + "/transport/converter/protobuf"
}

// Render whole grpc client file.
//
//		// This file was automatically generated by "microgen" utility.
//		// Please, do not edit.
//		package transportgrpc
//
//		import (
//			transportlayer "github.com/devimteam/go-kit/transportlayer"
//			grpc1 "github.com/devimteam/go-kit/transportlayer/grpc"
//			svc "github.com/devimteam/microgen/test/svc"
//			protobuf "github.com/devimteam/microgen/test/svc/transport/converter/protobuf"
//			grpc "google.golang.org/grpc"
//		)
//
//		func NewClient(conn *grpc.ClientConn) svc.StringService {
//			endpoints := []transportlayer.Endpoint{
//				transportlayer.NewEndpoint(
//					"Count",
//					nil,
//					transportlayer.WithConverter(protobuf.CountConverter),
// 				),
// 			}
//			return svc.NewClient(
//				grpc1.NewClient(
//					"devim.string.protobuf.StringService",
//					conn,
//					endpoints,
// 				),
// 			)
//		}
//
func (t *GRPCClientTemplate) Render(i *types.Interface) *Statement {
	t.packageName = "transportgrpc"
	f := Statement{}

	f.Func().Id("NewGRPCClient").
		Params(
			Id("conn").Op("*").Qual(PackagePathGoogleGRPC, "ClientConn"),
			Id("opts").Op("...").Qual(PackagePathGoKitTransportGRPC, "ClientOption"),
		).Qual(t.PackagePath, i.Name).
		BlockFunc(func(g *Group) {
			g.Return().Qual(t.PackagePath, "Endpoints").Values(DictFunc(func(d Dict) {
				for _, m := range i.Methods {
					d[Id(endpointStructName(m.Name))] = Qual(PackagePathGoKitTransportGRPC, "NewClient").Call(
						Line().Id("conn"),
						Line().Lit("devim."+strings.ToLower(strings.TrimSuffix(i.Name, "Service"))+".protobuf."+i.Name),
						Line().Lit(m.Name),
						Line().Qual(pathToConverter(t.PackagePath), encodeRequestName(m)),
						Line().Qual(pathToConverter(t.PackagePath), decodeResponseName(m)),
						Line().Add(t.replyType(m)),
						Line().Id("opts").Op("...").Line(),
					).Dot("Endpoint").Call()
				}
			}))
			/*g.Id("endpoints").Op(":=").Index().Qual(PackagePathTransportLayer, "Endpoint").ValuesFunc(func(group *Group) {
				for _, signature := range i.Methods {
					group.Line().Qual(PackagePathTransportLayer, "NewClient").Call(
						Line().Lit(signature.Name),
						Line().Nil(),
						Line().Qual(PackagePathTransportLayer, "WithConverter").Call(Qual(t.grpcConverterPackagePath(), converterStructName(signature))),
						Line(),
					)
				}
				group.Line()
			})
			g.Return().Qual(t.PackagePath, "NewClient").Call(
				Line().Qual(PackagePathTransportLayerGRPC, "NewClient").Call(
					Line().Lit("devim."+strings.ToLower(strings.TrimSuffix(i.Name, "Service"))+".protobuf."+i.Name),
					Line().Id("conn"),
					Line().Id("endpoints"),
					Line(),
				),
				Line(),
			)*/
		})
	return &f
}

// Renders reply type argument
// 		stringsvc.CountResponse{}
func (t *GRPCClientTemplate) replyType(signature *types.Function) *Statement {
	return Qual(protobufPath(t.ServicePackageName), responseStructName(signature)).Values()
}

func (GRPCClientTemplate) Path() string {
	return "./transport/grpc/client.go"
}

func (t *GRPCClientTemplate) PackageName() string {
	return t.packageName
}
