package template

import (
	. "github.com/dave/jennifer/jen"
	"github.com/devimteam/microgen/parser"
	"github.com/devimteam/microgen/util"
)

const (
	loggerVar      = "logger"
	nextVar        = "next"
	serviceLogging = "ServiceLogging"
)

type LoggingTemplate struct {
	PackagePath string
}

// Returns logging structure name by service interface.
func loggingStructName(iface *parser.Interface) string {
	return iface.Name + "LoggingMiddleware"
}

// Render all logging.go file.
//
//		// This file was automatically generated by "microgen" utility.
//		// Please, do not edit.
//		package stringsvc
//
//		import (
//			context "context"
//			svc "github.com/devimteam/microgen/test/svc"
//			log "github.com/go-kit/kit/log"
//			time "time"
//		)
//
//		func ServiceLogging(logger log.Logger) Middleware {
//			return func(next svc.StringService) svc.StringService {
//				return StringServiceLoggingMiddleware{
//					logger: logger,
//					next:   next,
//				}
//			}
//		}
//
//		type StringServiceLoggingMiddleware struct {
//			logger log.Logger
//			next   svc.StringService
//		}
//
//		func (s *StringServiceLoggingMiddleware) Count(ctx context.Context, text string, symbol string) (count int, positions []int) {
//			defer func(begin time.Time) {
//				s.logger.Log(
//					"method", "Count",
//					"text", text, "symbol", symbol,
//					"count", count, "positions", positions,
//					"took", time.Since(begin))
//			}(time.Now())
//			return s.next.Count(ctx, text, symbol)
//		}
//
func (t LoggingTemplate) Render(i *parser.Interface) *File {
	f := NewFile(i.PackageName)

	f.Func().Id(serviceLogging).Params(Id(loggerVar).Qual(PackagePathGoKitLog, "Logger")).Params(Id(MiddlewareTypeName)).
		Block(t.newLoggingBody(i))

	f.Line()

	// Render type logger
	f.Type().Id(loggingStructName(i)).Struct(
		Id(loggerVar).Qual(PackagePathGoKitLog, "Logger"),
		Id(nextVar).Qual(t.PackagePath, i.Name),
	)

	// Render functions
	for _, signature := range i.FuncSignatures {
		f.Line()
		f.Add(loggingFunc(signature, i))
	}

	return f
}

func (LoggingTemplate) Path() string {
	return "./middleware/logging.go"
}

// Render body for new logging middleware.
//
//		func ServiceLogging(logger log.Logger) Middleware {
//			return func(next svc.StringService) svc.StringService {
//				return StringServiceLoggingMiddleware{
//					logger: logger,
//					next:   next,
//				}
//			}
//		}
//
func (t LoggingTemplate) newLoggingBody(i *parser.Interface) *Statement {
	return Return(Func().Params(
		Id(nextVar).Qual(t.PackagePath, i.Name),
	).Params(
		Qual(t.PackagePath, i.Name),
	).BlockFunc(func(g *Group) {
		g.Return(Id(loggingStructName(i)).Values(
			Dict{
				Id(loggerVar): Id(loggerVar),
				Id(nextVar):   Id(nextVar),
			},
		))
	}))
}

// Render logging middleware for interface method.
//
//		func (s *StringServiceLogging) Count(ctx context.Context, text string, symbol string) (count int, positions []int) {
//			defer func(begin time.Time) {
//				s.logger.Log("method", "Count",
//					"text", text, "symbol", symbol,
//					"count", count, "positions", positions,
//					"took", time.Since(begin))
//			}(time.Now())
//			return s.next.Count(ctx, text, symbol)
//		}
//
func loggingFunc(signature *parser.FuncSignature, i *parser.Interface) *Statement {
	return methodDefinition(loggingStructName(i), signature).
		BlockFunc(loggingFuncBody(signature))
}

// Render parameters for function call.
//
//		ctx, text, symbol
//
func funcCallParamsByFields(fields []*parser.FuncField) *Statement {
	var list []Code
	for _, field := range fields {
		list = append(list, Id(util.ToLowerFirst(field.Name)))
	}
	return List(list...)
}

// Render logging function body with request/response and time tracking.
//
//		defer func(begin time.Time) {
//			s.logger.Log("method", "Count",
//				"text", text, "symbol", symbol,
//				"count", count, "positions", positions,
//				"took", time.Since(begin))
//		}(time.Now())
//		return s.next.Count(ctx, text, symbol)
//
func loggingFuncBody(signature *parser.FuncSignature) func(g *Group) {
	method, begin, took := "method", "begin", "took"
	return func(g *Group) {
		g.Defer().Func().Params(Id(begin).Qual(PackagePathTime, "Time")).Block( // defer func(begin time.Time) {
			Id(util.FirstLowerChar(serviceLogging)).Dot(loggerVar).Dot("Log").Call( // s.logger.Log(
				Line().Lit(method), Lit(signature.Name), // Method name
				Line().Add(paramsNameAndValue(signature.Params)),                 // Log request params
				Line().Add(paramsNameAndValue(signature.Results)),                // Log response params
				Line().Lit(took), Qual(PackagePathTime, "Since").Call(Id(begin)), // Track request duration
			), // )
		).Call(Qual(PackagePathTime, "Now").Call()) // }(time.Now())
		// return s.next.Count(ctx, text, symbol)
		g.Return().Id(util.FirstLowerChar(serviceLogging)).Dot(nextVar).Dot(signature.Name).Call(funcCallParamsByFields(signature.Params))
	}
}

// Renders key/value pairs wrapped in Dict for provided fields.
//
//		"err", err, "result", result,
//
func paramsNameAndValue(fields []*parser.FuncField) *Statement {
	return ListFunc(func(g *Group) {
		for i, field := range fields {
			if i == 0 && checkFieldIsContext(field) {
				continue
			}
			g.List(Lit(field.Name), Id(field.Name))
		}
	})
}
