// Code generated by microgen 1.0.0-alpha. DO NOT EDIT.

package service

import service "github.com/devimteam/microgen/examples/addsvc"

// Service middleware (closure).
type Middleware func(service.Service) service.Service
