// Code generated by microgen 0.9.0. DO NOT EDIT.

package service

import (
	"context"
	"fmt"
	service "github.com/devimteam/microgen/examples/addsvc/addsvc"
	log "github.com/go-kit/kit/log"
)

// RecoveringMiddleware recovers panics from method calls, writes to provided logger and returns the error of panic as method error.
func RecoveringMiddleware(logger log.Logger) Middleware {
	return func(next service.Service) service.Service {
		return &recoveringMiddleware{
			logger: logger,
			next:   next,
		}
	}
}

type recoveringMiddleware struct {
	logger log.Logger
	next   service.Service
}

func (M recoveringMiddleware) Sum(ctx context.Context, a int, b int) (result int, err error) {
	defer func() {
		if r := recover(); r != nil {
			M.logger.Log("method", "Sum", "message", r)
			err = fmt.Errorf("%v", r)
		}
	}()
	return M.next.Sum(ctx, a, b)
}

func (M recoveringMiddleware) Concat(ctx context.Context, a string, b string) (result string, err error) {
	defer func() {
		if r := recover(); r != nil {
			M.logger.Log("method", "Concat", "message", r)
			err = fmt.Errorf("%v", r)
		}
	}()
	return M.next.Concat(ctx, a, b)
}
